### ISSUE TITLE
Training of the models is getting failed

### ISSUE THREAD

**Issue by Ali-Xain** [Pratik-Barhate/question-classification#1]
Hi. I have cloned the question classification project and and setup successfully. But when i am trying to train SVM after executiung nlp, i am facing the following issue.   

Error:
raise ValueError("empty vocabulary; perhaps the documents only" 
ValueError: empty vocabulary; perhaps the documents only contain stop words. 

Full stack trace is given below:

* Training started - svm model
Traceback (most recent call last):
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/ml/__main__.py", line 12, in <module>
    train.execute(root_path, ml_algo)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/ml/train.py", line 80, in execute
    abbr_val = abbr_result.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/ml/train.py", line 26, in train_one_node
    x_ft = get_ft_obj("training", rp, ml_algo, cat_type)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/dataprep/feature_stack.py", line 38, in get_ft_obj
    nflag, n_ft = text_ft_arr(data_type, rp, "ner", ml_algo, cat_type)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/dataprep/text_features.py", line 46, in text_ft_arr
    vflag, vectorizer = get_vect(data_type, rp, prop_type, ml_algo, cat_type, ner_l)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/qc/dataprep/text_features.py", line 78, in get_vect
    count_vec = CountVectorizer(ngram_range=(1, 2)).fit(text_data)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/venv5/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 836, in fit
    self.fit_transform(raw_documents)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/venv5/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 869, in fit_transform
    self.fixed_vocabulary_)
  File "/home/legend/Desktop/python-2018-ali/pratik-question-classification-master/venv5/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 811, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words

Things i have tried so far:
1) To avoid conflict with the stop word list of sklearn, i have modified CountVectorizer through the addition  of stop word argument:  (stop_words=None)

kindly suggest a solution . 

Thanks.  Keep up the good work!

**Comment by PratikBarhate** [comment]
Hi Ali-Xian,

I will check the latest code and get back to you as soon as possible.
________________________________

**Comment by PratikBarhate** [comment]
@Ali-Xain 
I just ran the code again on my system it is working as expected. 
Check whether the `dataset` folder has same files in your system and NLP process is finishing without any error.
Maybe while cloning the process was not completed or some files were not cloned/cloned with some error. Can you please try executing the commands:-
1. `./bin/cleanup.sh all`
2. `./bin/qc.sh nlp`
3. `./bin/qc.sh train svm`

Or if you can do, is clone the project again and repeat the command sequence.
